# Generated by Django 2.0.7 on 2018-07-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='tests/%Y-%m-%d/%H-%i-%s/'),
        ),
    ]
