# Generated by Django 2.0.7 on 2018-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180726_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='detected',
            field=models.FileField(blank=True, upload_to='tests/detected/'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='tests/%Y-%m-%d/%H-%M-%S/'),
        ),
    ]
