# Generated by Django 2.0.7 on 2018-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectResModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField()),
                ('path', models.FilePathField(match='image.*\\.jpg$', path=None)),
            ],
        ),
    ]
