# Generated by Django 2.0.7 on 2018-07-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfileapp', '0002_detectresmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectresmodel',
            old_name='parent',
            new_name='parent_obj',
        ),
        migrations.RemoveField(
            model_name='detectresmodel',
            name='path',
        ),
        migrations.AddField(
            model_name='detectresmodel',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
